### GET request to example server
GET http://localhost:4000/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsInJvbGUiOiJTVFVERU5UIiwiZnVsbE5hbWUiOiJ0ZXN0MSIsImlhdCI6MTc1MzU0MTkxOSwiZXhwIjoxNzUzNTc3OTE5fQ.aqpT_zj2EMQ1X3N69Je79qq4mpY4lbDLmJw1NjCJpXU

###